apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoweb
  labels:
    app: webserver
  annotations:
    deployment.kubernetes.io/revision: "2"
    deployment.kubernetes.io/change-cause: "Upgrade echoweb to 2.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: echoweb
          image: jam13c/echoweb:2.0
          ports:
            - containerPort: 80
          env:
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: echoweb-svc
  labels:
    app: webserver
spec:
  type: NodePort 
  selector:
    app: webserver
  ports:
  - nodePort: 32003
    port: 80
    targetPort: 80
    protocol: TCP
 