apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config
  namespace: default
data:
  podId: "Jamie Demo Pod"
---
apiVersion: v1
kind: Pod
metadata:
  name: echoweb
  labels:
    app: webserver
spec:
  containers:
    - name: echoweb
      image: jam13c/echoweb:1.0
      ports:
        - containerPort: 80
      env:
      - name: POD_ID
        valueFrom:
          configMapKeyRef:
            name: custom-config
            key: podId