apiVersion: v1
kind: Pod
metadata:
  name: echoweb  
  labels:
    app: webserver
spec:
  containers:
    - name: echoweb
      image: jam13c/echoweb:2.0
      ports:
      - containerPort: 80
      env:
      - name: POD_ID
        value: "ReadinessPod"
      - name: READY_AFTER_SECONDS
        value: "15"
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3