apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoweb
  labels:
    app: webserver
  annotations:
    deployment.kubernetes.io/revision: "2"
    deployment.kubernetes.io/change-cause: "Upgrade echoweb to 2.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: echoweb
          image: jam13c/echoweb:2.0
          ports:
            - containerPort: 80
            